services:
  api:
    container_name: cromalink-api-users
    hostname: cromalink-api-users
    image: cromalink-api-users
    networks:
      - cromalink
    build:
      context: .
    env_file:
      - .env
    environment:
      - APP_NAME='Cromalink API'
      - DB_HOST=cromalink_db
      - DB_DATABASE=cromalink_db
      - DB_USERNAME=cromalink_user
      - DB_PASSWORD=Cr0m4l1nK.
      - DB_PORT=3306
      - APP_DEBUG=false
      - AUTH_API_URL=cromalink-api-auth/api/oauth

networks:
  cromalink:
    external: true
